张量的赋值与索引

In [13]:
import torch

b = torch.ones(3)   # 创建大小为3的一维张量, 用1.0填充
print(b)

print(b[1])
print(float(b[1]))  # 直接索引元素得到的还是张量, 需要转化成浮点型

tensor([1., 1., 1.])
tensor(1.)
1.0


In [14]:
b[2] = 2.0
print(b)
b[2] = torch.tensor(3.)
print(b)
b[2] = torch.tensor([4.])     # 把 python list 转化成张量
# ERROR: b[2] = torch.tensor([4., 5.])
print(b)

# 三种赋值方式等价

tensor([1., 1., 2.])
tensor([1., 1., 3.])
tensor([1., 1., 4.])


张量的形状

In [15]:
points = torch.tensor([[4.0, 1.0], [5.0, 2.0], [6.0, 3.0]])
print('Get shape: ', points.shape)   # 3行, 2列

print(points[0,1])   # 双索引, 0号列表里的1号元素, 从外往里数方括号

Get shape:  torch.Size([3, 2])
tensor(1.)


复习python列表索引

In [16]:
some_list = list(range(6))
print(some_list[:])
print(some_list[1:4])
print(some_list[:4])
print(some_list[:-1])
print(some_list[1:5:2])   # 1到5, 左闭右开, 步长为2

[0, 1, 2, 3, 4, 5]
[1, 2, 3]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]
[1, 3]


命名张量的维度

In [21]:
img_t = torch.randn(3, 5, 5)        # Shape (channels, rows, columns)
print(img_t.shape, img_t)
batch_t = torch.randn(2, 3, 5, 5)   # Shape (batch, channels, rows, columns <- 这个叫作第四个维度的数量)
# print('batch_t: ',batch_t)

img_gray_naive = img_t.mean(-3)
# 消除倒数第三个维度. 假设这个维度的数量是3, 把这个维度上的每3个值叠起来用一个平均值代替. 
batch_gray_naive = batch_t.mean(-3)
print(img_gray_naive.shape, img_gray_naive)
# print(batch_gray_naive.shape, batch_gray_naive)

torch.Size([3, 5, 5]) tensor([[[-0.8005,  0.2126,  0.6393, -0.5141,  1.0192],
         [-0.2104, -0.5836,  0.9369, -1.2296,  0.0035],
         [ 0.2587, -0.5218, -1.4050, -1.2024,  0.4213],
         [ 0.1904, -0.8433,  1.7315,  1.4248, -0.0919],
         [-0.3526, -0.1195,  0.1268, -0.0526,  1.2233]],

        [[-0.6718, -0.6073,  0.0983,  3.0248, -1.5247],
         [ 1.6705,  0.6429,  0.3485,  0.2379, -0.7924],
         [-0.4174, -1.0078,  1.1660, -0.3046, -0.4887],
         [-0.0539,  1.8971,  0.2826, -0.1701, -1.2651],
         [ 0.0853, -1.8277, -0.9421, -0.9462, -1.3493]],

        [[-0.7755,  1.4155, -0.8846, -1.1090, -0.7678],
         [-0.7022, -0.1152, -0.1823,  0.4114, -0.5163],
         [-0.6137,  0.0217, -1.2823, -1.4639, -0.2829],
         [ 0.5612,  0.1030,  1.2911,  0.2326,  0.0277],
         [-1.5713, -0.4111, -1.1641, -0.9201,  2.0845]]])
torch.Size([5, 5]) tensor([[-0.7493,  0.3403, -0.0490,  0.4672, -0.4244],
        [ 0.2526, -0.0186,  0.3677, -0.1935, -0.4351],
   

```
升维
torch.unsqueeze(
	input, 
	dim, 	     # dim 从0算起, 将要扩增的维度【必填】
	out = None)
如果dim为负, 则将会被转化dim+input.dim()+1, 即在最后增一维

降维
torch.squeeze(
    input, 
	dim, 	     # dim 从0算起, 将要挤压的维度【必填】
	out = None)
如果dim指定的维度的值为1, 则将该维度删除, 若指定的维度值不为1, 则返回原来的tensor

unsqueeze_ 和 unsqueeze 实现一样的功能, 
区别在于 unsqueeze 不会对使用 unsqueeze 的 tensor 进行改变, 想要获取 unsqueeze 后的值必须赋予个新值, 
unsqueeze_ 则会对自己改变. 
```

In [27]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])
# 我们可以对相同形状的张量进行乘法运算, 所以需要对张量进行升维/降维

unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)  # 在最后(即最小维度)升两维
print(unsqueezed_weights)

img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
# batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])
